import { createSlice } from '@reduxjs/toolkit';
import _ from 'lodash';
import { RootState } from '../../app/store';

export interface FiltersState {
  groupByRegions: boolean;
}

const initialState: FiltersState = {
  groupByRegions: false
};

export const filtersSlice = createSlice({
  name: 'filters',
  initialState,
  reducers: {
    groupByRegions: (state) => {
      state.groupByRegions = true;
    },
    showAsIndividualStations: (state) => {
      state.groupByRegions = false;
    },
    toggleGroupByRegions: (state) => {
      state.groupByRegions = !state.groupByRegions;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
  },
});

export const { groupByRegions, showAsIndividualStations, toggleGroupByRegions } = filtersSlice.actions;

export const selectGroupByRegions = (state: RootState) => state.filters.groupByRegions;

// TODO Add action for updating data if old

export default filtersSlice.reducer;
