import { createSlice, PayloadAction } from '@reduxjs/toolkit';
import _ from 'lodash';
import { RootState } from '../../app/store';
import { selectRegions } from '../police/policeSlice';

export interface FiltersState {
  groupByRegions: boolean;
  visibleRegions: string[];
  visibleStations: string[];
}

const initialState: FiltersState = {
  groupByRegions: false,
  visibleRegions: [],
  visibleStations: []
};

export const filtersSlice = createSlice({
  name: 'filters',
  initialState,
  reducers: {
    groupByRegions: (state) => {
      state.groupByRegions = true;
    },
    showAsIndividualStations: (state) => {
      state.groupByRegions = false;
    },
    toggleGroupByRegions: (state) => {
      state.groupByRegions = !state.groupByRegions;
    },
    setVisibleRegions: (state, action: PayloadAction<string[]>) => {
      state.visibleRegions = action.payload;
    },
    setVisibleStations: (state, action: PayloadAction<string[]>) => {
      state.visibleStations = action.payload;
    }
  },
  // The `extraReducers` field lets the slice handle actions defined elsewhere,
  // including actions generated by createAsyncThunk or in other slices.
  extraReducers: (builder) => {
  },
});

export const {
  groupByRegions,
  showAsIndividualStations,
  toggleGroupByRegions,
  setVisibleRegions,
  setVisibleStations } = filtersSlice.actions;

export const selectGroupByRegions = (state: RootState) => state.filters.groupByRegions;
export const selectVisibleRegions = (state: RootState) => _.isEmpty(state.filters.visibleRegions) ? selectRegions(state) : state.filters.visibleRegions;
export const selectVisibleStations = (state: RootState) => state.filters.visibleStations;

// TODO Add action for updating data if old

export default filtersSlice.reducer;
