# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/github/administering-a-repository/configuration-options-for-dependency-updates

version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/frontend"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(frontend):"
    labels:
      - "frontend"
  - package-ecosystem: "npm"
    directory: "/backend"
    open-pull-requests-limit: 20
    schedule:
      interval: "daily"
    commit-message:
      prefix: "fix(backend):"
    labels:
      - "backend"
