name: Build and Release
on:
  push:
    branches:
    - main

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Build and publish frontend
      uses: VaultVulp/gp-docker-action@1.6.0
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        image-name: police-appointment-times
        build-context: ./frontend
        image-tag: ${{ github.sha }}
    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 18
    - name: Release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_USERNAME: ${{ github.actor }}
        DOCKER_PASSWORD: ${{ secrets.GITHUB_TOKEN }}
      run: |
        npx \
          -p conventional-changelog-conventionalcommits \
          -p @semantic-release-plus/docker \
          -p semantic-release \
          semantic-release
